# Generated by Django 3.2.13 on 2022-05-20 20:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Citizen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("context", models.JSONField(null=True)),
                ("first_name", models.CharField(max_length=100)),
                ("first_surname", models.CharField(max_length=100)),
                (
                    "last_surname",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "citizen",
                "verbose_name_plural": "citizens",
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("context", models.JSONField(null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("url", models.URLField()),
                (
                    "social_network",
                    models.CharField(
                        choices=[
                            ("facebook", "facebook"),
                            ("twitter", "twitter"),
                            ("youtube", "youtube"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_networks",
                        to="citizens.citizen",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
